export const MAIN_PAGE_TYPES = {
    GET_CATS_REQUEST: 'MAIN_PAGE_TYPES.GET_CATS_REQUEST',
    GET_CATS_SUCCESS: 'MAIN_PAGE_TYPES.GET_CATS_SUCCESS',
    GET_CATS_FAIL: 'MAIN_PAGE_TYPES.GET_CATS_FAIL',
}