export const LAYOUT_STANDARD_TYPES = {
    GET_CATEGORIES_REQUEST: 'LAYOUT_STANDARD_TYPES.GET_CATEGORIES_REQUEST',
    GET_CATEGORIES_SUCCESS: 'LAYOUT_STANDARD_TYPES.GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_FAIL: 'LAYOUT_STANDARD_TYPES.GET_CATEGORIES_FAIL',
}