export const SIDEBAR_TYPES = {
    GET_CATEGORIES_REQUEST: 'SIDEBAR_TYPES.GET_CATEGORIES_REQUEST',
    GET_CATEGORIES_SUCCESS: 'SIDEBAR_TYPES.GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_FAIL: 'SIDEBAR_TYPES.GET_CATEGORIES_FAIL',
    SET_SELECTED_CATEGORIES: 'SIDEBAR_TYPES.SET_SELECTED_CATEGORIES'
}